default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: semana_development
  #url: 'postgres://gtijr:papa12369@mygti.cwxgcpy6bi6a.us-east-1.rds.amazonaws.com:5432/gti_db'
test:
  <<: *default
  database: semana_test
production:
  <<: *default
  database: semana_production
  username: semanas
  password: <%= ENV['CONCEITO_DATABASE_PASSWORD'] %>
  #url: <%= ENV['HEROKU_POSTGRESQL_GTI_URL'] %>
