stem:
  <<: *default
  name: Semana de Tecnologia da Engenharia Mec창nica
  sigla: STEM
  colors:
    primary: 871328
    default: 871328
  logo: stem-logo.png
  infos:
    conta: 23857-X
    agencia: 4439-3
    beneficiado: Laylla Sharon Bezerra Peixoto
    banco: Banco do Brasil
    local: PET da Engenharia Mec창nica

# Config.create(name: 'Semana de Tecnologia da Engenharia Mec창nica', sigla: 'STEM', conta: '23857-X',
# agencia: '4439-3', beneficiado: 'Laylla Sharon Bezerra Peixoto', banco: 'banco', local: 'PET da Engenharia Mec창nica',
# email: 'pixelzip0@gmail.com')